### ISSUE TITLE
Crash when opening a particular savestate

### ISSUE THREAD

**Issue by spectromas** [BespokeSynth/BespokeSynth#132]
Yesterday I was creating a patch, saved it, closed Bespoke and then tried to come back to it later on but every time I try to load it now it crashes. I know that one other linux user has reproduced this. This is the crash log: 

```
backtrace:
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0xa3e4f4) [0x558b231ea4f4]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x89e3f5) [0x558b2304a3f5]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0xa2c151) [0x558b231d8151]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0) [0x7f9520af23c0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7f952053718b]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7f9520516859]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9e911) [0x7f952079e911]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa38c) [0x7f95207aa38c]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa3f7) [0x7f95207aa3f7]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa6a9) [0x7f95207aa6a9]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x24d4ba) [0x558b229f94ba]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x8c6627) [0x558b23072627]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x86da49) [0x558b23019a49]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x8a2ab2) [0x558b2304eab2]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x8b3158) [0x558b2305f158]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x8a4243) [0x558b23050243]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x8a51d3) [0x558b230511d3]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x8a8e9f) [0x558b23054e9f]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x8a9437) [0x558b23055437]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x8a973f) [0x558b2305573f]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x888c7d) [0x558b23034c7d]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0xaddcf1) [0x558b23289cf1]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0xadda2a) [0x558b23289a2a]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0xadc448) [0x558b23288448]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x36c451) [0x558b22b18451]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f95205180b3]
/home/alex/Downloads/BespokeSynth/BespokeSynth(+0x36f36e) [0x558b22b1b36e]



OS: Linux
CPU vendor: GenuineIntel
CPU model: Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
CPU speed: 1300 MHz
num cores: 8
num CPUs: 4
RAM: 11908 MB
computer: hyperion-laptop
language: British English
region: United Kingdom
display language: British English-United Kingdom
description: 
manufacturer: 
build: bespoke 1.0.0 (Sep 13 2021 21:54:44)
```

Running from a terminal I see this output: 

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Type is not convertible to string
Killed
```

This is the savestate: 
[Karp.zip](https://github.com/awwbees/BespokeSynth/files/7175973/Karp.zip)

Info: 
```
System:    Host: hyperion-laptop Kernel: 5.11.0-34-lowlatency x86_64 bits: 64 compiler: N/A Desktop: KDE Plasma 5.22.5 
           Distro: KDE neon 20.04 5.22 base: Ubuntu 20.04 LTS Focal 
Machine:   Type: Laptop System: Hewlett-Packard product: HP EliteBook 8570w v: A1029D1102 serial: <superuser/root required> 
           Mobo: Hewlett-Packard model: 176B v: KBC Version 50.1B serial: <superuser/root required> BIOS: Hewlett-Packard 
           v: 68IAV Ver. F.41 date: 05/20/2013 
Battery:   ID-1: BAT0 charge: 60.1 Wh condition: 63.0/63.0 Wh (100%) model: Hewlett-Packard Primary status: Unknown 
CPU:       Topology: Quad Core model: Intel Core i7-3720QM bits: 64 type: MT MCP arch: Ivy Bridge rev: 9 L2 cache: 6144 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 41504 
           Speed: 1289 MHz min/max: 1200/3600 MHz Core speeds (MHz): 1: 1378 2: 1421 3: 1389 4: 1307 5: 1418 6: 1654 7: 2188 
           8: 1391 
Graphics:  Device-1: NVIDIA GK107GLM [Quadro K2000M] vendor: Hewlett-Packard driver: nvidia v: 470.63.01 bus ID: 01:00.0 
           Display: x11 server: X.Org 1.20.11 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: Quadro K2000M/PCIe/SSE2 v: 4.6.0 NVIDIA 470.63.01 direct render: Yes 
Audio:     Device-1: Intel 7 Series/C216 Family High Definition Audio vendor: Hewlett-Packard driver: snd_hda_intel v: kernel 
           bus ID: 00:1b.0 
           Device-2: NVIDIA GK107 HDMI Audio vendor: Hewlett-Packard driver: snd_hda_intel v: kernel bus ID: 01:00.1 
           Sound Server: ALSA v: k5.11.0-34-lowlatency 
Network:   Device-1: Intel 82579LM Gigabit Network vendor: Hewlett-Packard driver: e1000e v: kernel port: 5040 bus ID: 00:19.0 
           IF: enp0s25 state: down mac: 2c:44:fd:65:23:13 
           Device-2: Intel Centrino Ultimate-N 6300 driver: iwlwifi v: kernel port: 4000 bus ID: 25:00.0 
           IF: wlo1 state: up mac: 3c:a9:f4:4f:0d:0c 
Drives:    Local Storage: total: 1.14 TiB used: 892.30 GiB (76.6%) 
           ID-1: /dev/sda vendor: Crucial model: CT250MX500SSD1 size: 232.89 GiB temp: 40 C 
           ID-2: /dev/sdb vendor: Toshiba model: MQ01ABD100 size: 931.51 GiB temp: 31 C 
Partition: ID-1: / size: 114.75 GiB used: 59.31 GiB (51.7%) fs: ext4 dev: /dev/sda2 
Sensors:   System Temperatures: cpu: 58.0 C mobo: 54.0 C gpu: nvidia temp: 52 C 
           Fan Speeds (RPM): N/A 
Info:      Processes: 269 Uptime: 1d 4h 42m Memory: 11.63 GiB used: 4.04 GiB (34.7%) Init: systemd runlevel: 5 Compilers: 
           gcc: 9.3.0 Shell: bash v: 5.0.17 inxi: 3.0.38 
```

**Comment by KottV** [comment]
here is the backtrace:
```
Thread 1 "BespokeSynth-de" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
Missing separate debuginfos, use: zypper install libXfixes3-debuginfo-6.0.0-1.2.x86_64 libXinerama1-debuginfo-1.1.4-1.11.x86_64
--Type <RET> for more, q to quit, c to continue without paging--
49        return ret;
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff7441864 in __GI_abort () at abort.c:79
#2  0x00007ffff76b09b6 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff76bc19c in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff76bc207 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007ffff76bc4a9 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x1193120 <typeinfo for std::runtime_error@GLIBCXX_3.4>, dest=0x7ffff76d1010 <std::runtime_error::~runtime_error()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x0000000000430e1a in Json::Value::asString[abi:cxx11]() const (this=<optimized out>) at ../../Source/json/src/lib_json/json_value.cpp:700
#7  0x00000000009b97fb in ModuleSaveData::LoadString (this=this@entry=0x1cc2f58, prop=..., moduleInfo=..., defaultValue=..., fillFn=fillFn@entry=0x0) at ../../Source/ModuleSaveData.cpp:233
#8  0x0000000000968e5c in FloatSliderLFOControl::LoadLayout (this=0x1cc2b20, moduleInfo=...) at ../../Source/FloatSliderLFOControl.cpp:426
#9  0x0000000000999270 in ModularSynth::SetUpModule (this=0x1336f70, module=<optimized out>, moduleInfo=...) at ../../Source/ModularSynth.cpp:2042
#10 0x00000000009a70e4 in ModuleContainer::LoadModules (this=this@entry=0x1337820, modules=...) at ../../Source/ModuleContainer.cpp:502
#11 0x000000000099b75b in ModularSynth::LoadLayout (this=0x1336f70, json=...) at ../../Source/ModularSynth.cpp:1971
#12 0x000000000099c41d in ModularSynth::LoadLayoutFromString (this=0x1336f70, jsonString=...) at ../../Source/ModularSynth.cpp:1955
#13 0x000000000099f6ac in ModularSynth::LoadState (this=0x1336f70, file=...) at ../../Source/ModularSynth.cpp:2319
#14 0x000000000099fc01 in ModularSynth::LoadStatePopupImp (this=0x1336f70) at ../../Source/ModularSynth.cpp:2272
#15 0x000000000099ff6f in ModularSynth::Poll (this=0x1336f70) at ../../Source/ModularSynth.cpp:370
#16 0x00000000009809d9 in non-virtual thunk to MainContentComponent::timerCallback() ()
#17 0x0000000000bb4755 in juce::Timer::TimerThread::callTimers (this=0x13246f0) at /usr/src/JUCE-6.0.8/modules/juce_events/timers/juce_Timer.cpp:114
#18 0x0000000000bb4a3a in juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}::operator()(int) const (__closure=0x1309f68, fd=4) at /usr/src/JUCE-6.0.8/modules/juce_events/native/juce_linux_Messaging.cpp:43
#19 0x0000000000bb4c13 in std::function<void (int)>::operator()(int) const (__args#0=<optimized out>, this=0x1309f68) at /usr/include/c++/11/bits/std_function.h:560
#20 juce::InternalRunLoop::dispatchPendingEvents (this=this@entry=0x1309ee0) at /usr/src/JUCE-6.0.8/modules/juce_events/native/juce_linux_Messaging.cpp:186
#21 0x0000000000bb2b36 in juce::MessageManager::dispatchNextMessageOnSystemQueue (returnIfNoPendingMessages=returnIfNoPendingMessages@entry=false) at /usr/src/JUCE-6.0.8/modules/juce_events/native/juce_linux_Messaging.cpp:300
#22 0x0000000000bb2c87 in juce::MessageManager::runDispatchLoop (this=0x1309e70) at /usr/src/JUCE-6.0.8/modules/juce_events/messages/juce_MessageManager.cpp:128
#23 0x000000000053bb8e in juce::JUCEApplicationBase::main () at /usr/src/JUCE-6.0.8/modules/juce_events/messages/juce_ApplicationBase.cpp:262
#24 0x00007ffff7442b35 in __libc_start_main (main=0x51f530 <main(int, char**)>, argc=1, argv=0x7fffffffda98, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffda88) at ../csu/libc-start.c:332
#25 0x000000000053e9ae in _start () at ../sysdeps/x86_64/start.S:120
```

**Comment by KottV** [comment]
another example
```
Thread 1 "BespokeSynth-de" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49        return ret;
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff7441864 in __GI_abort () at abort.c:79
#2  0x00007ffff76b09b6 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff76bc19c in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff76bc207 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007ffff76bc4a9 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x120bf50 <typeinfo for LoadStateException>, dest=0x9aa1d0 <LoadStateException::~LoadStateException()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x000000000045d4ab in LoadStateValidate (assertion=<optimized out>) at ../../Source/SynthGlobals.cpp:736
#7  0x000000000096709b in FileStreamIn::operator>> (this=this@entry=0x7fffffffd380, var=...) at ../../Source/FileStream.cpp:138
#8  0x00000000009a7c96 in ModuleContainer::LoadState (this=0x7fffffffd160, this@entry=0x13379c0, in=...) at ../../Source/ModuleContainer.cpp:622
#9  0x000000000099f8ab in ModularSynth::LoadState (this=0x1337110, file=...) at ../../Source/ModularSynth.cpp:2324
#10 0x000000000099fc01 in ModularSynth::LoadStatePopupImp (this=0x1337110) at ../../Source/ModularSynth.cpp:2272
#11 0x000000000099ff6f in ModularSynth::Poll (this=0x1337110) at ../../Source/ModularSynth.cpp:370
#12 0x00000000009809d9 in non-virtual thunk to MainContentComponent::timerCallback() ()
#13 0x0000000000bb4755 in juce::Timer::TimerThread::callTimers (this=0x13246f0) at /usr/src/JUCE-6.0.8/modules/juce_events/timers/juce_Timer.cpp:114
#14 0x0000000000bb4a3a in juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}::operator()(int) const (__closure=0x1309f68, fd=4) at /usr/src/JUCE-6.0.8/modules/juce_events/native/juce_linux_Messaging.cpp:43
#15 0x0000000000bb4c13 in std::function<void (int)>::operator()(int) const (__args#0=<optimized out>, this=0x1309f68) at /usr/include/c++/11/bits/std_function.h:560
#16 juce::InternalRunLoop::dispatchPendingEvents (this=this@entry=0x1309ee0) at /usr/src/JUCE-6.0.8/modules/juce_events/native/juce_linux_Messaging.cpp:186
#17 0x0000000000bb2b36 in juce::MessageManager::dispatchNextMessageOnSystemQueue (returnIfNoPendingMessages=returnIfNoPendingMessages@entry=false) at /usr/src/JUCE-6.0.8/modules/juce_events/native/juce_linux_Messaging.cpp:300
#18 0x0000000000bb2c87 in juce::MessageManager::runDispatchLoop (this=0x1309e70) at /usr/src/JUCE-6.0.8/modules/juce_events/messages/juce_MessageManager.cpp:128
#19 0x000000000053bb8e in juce::JUCEApplicationBase::main () at /usr/src/JUCE-6.0.8/modules/juce_events/messages/juce_ApplicationBase.cpp:262
#20 0x00007ffff7442b35 in __libc_start_main (main=0x51f530 <main(int, char**)>, argc=1, argv=0x7fffffffda98, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffda88) at ../csu/libc-start.c:332
#21 0x000000000053e9ae in _start () at ../sysdeps/x86_64/start.S:120
(gdb) 
```
[AmbientTest.zip](https://github.com/awwbees/BespokeSynth/files/7178507/AmbientTest.zip)

**Comment by spectromas** [comment]
This has been fixed for me in the latest git build. I tried to open the project on the off chance and it opened up fine. 

@KottV do you have a copy of the other project you posted about? The zip here doesn't exist apparently.

**Comment by spectromas** [comment]
Ok I'm going to close this, seems like something has improved in this area and I'm unable replicate it now.
