### ISSUE TITLE
Is control feedback allowed? Crash when routing Songbuilder to itself (sometimes)

### ISSUE THREAD

**Issue by unfa** [BespokeSynth/BespokeSynth#1665]
## Describe the bug

I have mistakenly released my mouse button so that I dropped the end of a control plug onto the song builder's scene playback button, which resulted in a crash.

![image](https://github.com/user-attachments/assets/ad81b8e9-93e3-4887-9a3d-b73e8877d27d)

```gdb
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff6ea5463 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007ffff6e4c120 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff6e334c3 in __GI_abort () at abort.c:79
#4  0x00007ffff70d3af0 in std::__glibcxx_assert_fail (file=file@entry=0x555555e7c1f8 "/usr/include/c++/14.2.1/bits/stl_vector.h", line=line@entry=1130, 
    function=function@entry=0x555555e8f2c0 "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = SongBuilder::ControlTarget*; _Alloc = std::allocator<SongBuilder::ControlTarget*>; reference = SongBuild"..., condition=condition@entry=0x555555e6d955 "__n < this->size()") at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/assert_fail.cc:41
#5  0x0000555555b11ff1 in std::vector<SongBuilder::ControlTarget*, std::allocator<SongBuilder::ControlTarget*> >::operator[] (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/14.2.1/bits/stl_vector.h:1128
#6  std::vector<SongBuilder::ControlTarget*, std::allocator<SongBuilder::ControlTarget*> >::operator[] (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/14.2.1/bits/stl_vector.h:1128
#7  SongBuilder::PostRepatch (this=0x55555b77ce50, cable=<optimized out>, fromUserClick=<optimized out>) at /usr/src/debug/bespokesynth/bespokesynth/Source/SongBuilder.cpp:429
#8  0x0000555555a3c3c1 in PatchCableSource::RemovePatchCable (this=0x55555b89ed40, cable=0x55555b89e8a0, fromUserAction=<optimized out>) at /usr/src/debug/bespokesynth/bespokesynth/Source/PatchCableSource.cpp:683
#9  0x0000555555a40a87 in PatchCable::Destroy (this=<optimized out>, fromUserClick=true) at /usr/src/debug/bespokesynth/bespokesynth/Source/PatchCable.cpp:719
#10 0x0000555555a411fe in PatchCable::MouseReleased (this=<optimized out>) at /usr/src/debug/bespokesynth/bespokesynth/Source/PatchCable.cpp:457
#11 PatchCableSource::MouseReleased (this=<optimized out>) at /usr/src/debug/bespokesynth/bespokesynth/Source/PatchCableSource.cpp:499
#12 0x0000555555756e49 in IDrawableModule::MouseReleased (this=<optimized out>) at /usr/src/debug/bespokesynth/bespokesynth/Source/IDrawableModule.cpp:696
#13 0x0000555555756dae in IDrawableModule::MouseReleased (this=0x5555596ee820) at /usr/src/debug/bespokesynth/bespokesynth/Source/IDrawableModule.cpp:693
#14 0x0000555555a4bcca in Prefab::MouseReleased (this=0x5555596ee820) at /usr/src/debug/bespokesynth/bespokesynth/Source/Prefab.cpp:143
#15 0x00005555559a8fce in ModuleContainer::MouseReleased (this=0x55555677f9b0) at /usr/src/debug/bespokesynth/bespokesynth/Source/ModuleContainer.cpp:204
#16 0x000055555579b638 in ModuleContainer::MouseReleased (this=0x55555677f9b0) at /usr/src/debug/bespokesynth/bespokesynth/Source/ModularSynth.cpp:1953
#17 ModularSynth::MouseReleased (this=0x55555677f188, intX=<optimized out>, intY=<optimized out>, button=1, source=...) at /usr/src/debug/bespokesynth/bespokesynth/Source/ModularSynth.cpp:1950
#18 MainContentComponent::mouseUp (this=0x55555677ec80, e=...) at /usr/src/debug/bespokesynth/bespokesynth/Source/MainComponent.cpp:427
#19 0x0000555555c9a8f7 in juce::Component::internalMouseUp (this=0x55555677ec80, source=..., relativePointerState=..., time=..., oldModifiers=...) at /usr/share/juce/modules/juce_gui_basics/components/juce_Component.cpp:2225
#20 0x0000555555c7368f in juce::detail::MouseInputSourceImpl::setButtons (this=0x555556439b10, pointerState=..., time=..., newButtonState=...) at /usr/share/juce/modules/juce_gui_basics/detail/juce_MouseInputSourceImpl.h:151
#21 0x0000555555dc62ca in juce::detail::MouseInputSourceImpl::handleEvent (pen=..., newPressure=0, newOrientation=0, this=0x555556439b10, newPeer=..., positionWithinPeer=..., time=..., newMods=...)
    at /usr/share/juce/modules/juce_gui_basics/detail/juce_MouseInputSourceImpl.h:331
#22 juce::MouseInputSource::handleEvent (this=<optimized out>, pressure=0, orientation=0, peer=..., pos=..., time=1728831469722, mods=..., penDetails=...) at /usr/share/juce/modules/juce_gui_basics/mouse/juce_MouseInputSource.cpp:80
#23 juce::ComponentPeer::handleMouseEvent(juce::MouseInputSource::InputSourceType, juce::Point<float>, juce::ModifierKeys, float, float, long long, juce::PenDetails, int) [clone .constprop.0] (this=this@entry=0x555556c797e0, pos=..., 
    newMods=..., time=1728831469722, pen=..., touchIndex=0, newOrientation=0, newPressure=0, type=juce::MouseInputSource::mouse) at /usr/share/juce/modules/juce_gui_basics/windows/juce_ComponentPeer.cpp:90
#24 0x0000555555d372b3 in juce::XWindowSystem::handleButtonReleaseEvent (this=<optimized out>, peer=<optimized out>, buttonRelEvent=...) at /usr/share/juce/modules/juce_gui_basics/native/juce_XWindowSystem_linux.cpp:3638
#25 juce::XWindowSystem::handleWindowMessage (this=<optimized out>, peer=<optimized out>, event=...) at /usr/share/juce/modules/juce_gui_basics/native/juce_XWindowSystem_linux.cpp:3370
#26 juce::XWindowSystem::windowMessageReceive (event=...) at /usr/share/juce/modules/juce_gui_basics/native/juce_XWindowSystem_linux.cpp:3967
#27 juce::XWindowSystem::windowMessageReceive (event=...) at /usr/share/juce/modules/juce_gui_basics/native/juce_XWindowSystem_linux.cpp:3942
#28 operator() (__closure=<optimized out>) at /usr/share/juce/modules/juce_gui_basics/native/juce_XWindowSystem_linux.cpp:3292
#29 std::__invoke_impl<void, juce::XWindowSystem::initialiseXDisplay()::<lambda(int)>&, int> (__f=...) at /usr/include/c++/14.2.1/bits/invoke.h:61
#30 std::__invoke_r<void, juce::XWindowSystem::initialiseXDisplay()::<lambda(int)>&, int> (__fn=...) at /usr/include/c++/14.2.1/bits/invoke.h:111
#31 std::_Function_handler<void(int), juce::XWindowSystem::initialiseXDisplay()::<lambda(int)> >::_M_invoke(const std::_Any_data &, int &&) (__functor=..., __args#0=<optimized out>) at /usr/include/c++/14.2.1/bits/std_function.h:290
#32 0x0000555555bbfb77 in std::function<void(int)>::operator() (this=<optimized out>, __args#0=<optimized out>) at /usr/include/c++/14.2.1/bits/std_function.h:591
#33 operator() (__closure=<optimized out>) at /usr/share/juce/modules/juce_events/native/juce_Messaging_linux.cpp:360
#34 std::__invoke_impl<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()>&> (__f=...) at /usr/include/c++/14.2.1/bits/invoke.h:61
#35 std::__invoke_r<void, juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()>&> (__fn=...) at /usr/include/c++/14.2.1/bits/invoke.h:111
#36 std::_Function_handler<void(), juce::LinuxEventLoop::registerFdCallback(int, std::function<void(int)>, short int)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/14.2.1/bits/std_function.h:290
#37 0x0000555555bc9965 in std::function<void()>::operator() (this=<optimized out>) at /usr/include/c++/14.2.1/bits/std_function.h:591
#38 juce::InternalRunLoop::dispatchPendingEvents (this=0x5555562af020) at /usr/share/juce/modules/juce_events/native/juce_Messaging_linux.cpp:180
#39 juce::detail::dispatchNextMessageOnSystemQueue (returnIfNoPendingMessages=<optimized out>) at /usr/share/juce/modules/juce_events/native/juce_Messaging_linux.cpp:342
#40 0x000055555563a007 in juce::MessageManager::runDispatchLoop (this=<optimized out>) at /usr/share/juce/modules/juce_events/messages/juce_MessageManager.cpp:112
#41 juce::JUCEApplicationBase::main () at /usr/share/juce/modules/juce_events/messages/juce_ApplicationBase.cpp:265
#42 juce::JUCEApplicationBase::main (argc=<optimized out>, argv=<optimized out>) at /usr/share/juce/modules/juce_events/messages/juce_ApplicationBase.cpp:243
#43 main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/bespokesynth/bespokesynth/Source/Main.cpp:134
(gdb) 
```

## Build info

bespoke 1.2.1 (Sep 14 2024 10:42:14) - Linux - makepkg 9a2072ed

## Steps To Reproduce
1. Create a songbuilder moduke,
2. Add a parameter to it and assign it to the songbuilder's own play button.
3. This might crash but it's not consistent.

## Expected vs. actual behavior
I'd expect the control assignment to fail gracefully with an error message like "control feedback loop prevented".
I would expect routing control signals from a module back to itself to generally be disallowed, but it seems to not be, which might cause crashes in certain conditions.

**Comment by NoxyNixie** [comment]
Interesting. On my end I can't connect from the songbuilder to itself and I don't think something changed with that since September 14th (which is your build).

I however did find a bug where dropping a cable without connecting to control would crash. This I will resolve shortly in a PR.
