### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by djdeath** [BespokeSynth/BespokeSynth#33]
Sorry, I didn't save the thing that created this crash, hopefully the backtrace sheds some light on what went wrong :

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000565195aec372 in EffectChain::Process (this=0x565197a07580, time=3520822.4058407834) at ../../Source/EffectChain.cpp:146
146	../../Source/EffectChain.cpp: No such file or directory.
[Current thread is 1 (LWP 243921)]
(gdb) bt
#0  0x0000565195aec372 in EffectChain::Process (this=0x565197a07580, time=3520822.4058407834) at ../../Source/EffectChain.cpp:146
#1  0x0000565195c3ab82 in ModularSynth::AudioOut (this=0x565197330270, output=0x7f6b5c813e50, bufferSize=128, nChannels=8)
    at ../../Source/ModularSynth.cpp:1105
#2  0x0000565195cbade3 in juce::AudioDeviceManager::audioDeviceIOCallbackInt (this=0x56519732ff30, inputChannelData=0x7f6b50001830, numInputChannels=8, 
    outputChannelData=0x7f6b5c813e50, numOutputChannels=8, numSamples=128)
    at /home/awwbees/JUCE/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp:812
#3  0x0000565195cb562e in juce::(anonymous namespace)::ALSAThread::run (this=0x7f6b5c7a38d0)
    at /home/awwbees/JUCE/modules/juce_audio_devices/native/juce_linux_ALSA.cpp:716
#4  0x0000565195d90d41 in juce::Thread::threadEntryPoint (this=0x7f6b5c7a38d0) at /home/awwbees/JUCE/modules/juce_core/threads/juce_Thread.cpp:98
#5  0x0000565195d90ed9 in juce::juce_threadEntryPoint (userData=<optimized out>) at /home/awwbees/JUCE/modules/juce_core/threads/juce_Thread.cpp:121
#6  juce::threadEntryProc (userData=<optimized out>) at /home/awwbees/JUCE/modules/juce_core/native/juce_posix_SharedCode.h:834
#7  0x00007f6bb10adea7 in ?? ()
#8  0x0000000000000000 in ?? ()
```

**Comment by djdeath** [comment]
This is with the latest release btw.

**Comment by djdeath** [comment]
Closing, I'll try to get reproducer.
