### ISSUE TITLE
input module make bespokesynth hangs under jack audio

### ISSUE THREAD

**Issue by ycollet** [BespokeSynth/BespokeSynth#663]
I use BespokeSynth 1.1.0 under Fedora 34 using a Scarlett 18i8 sound card.
When I try to use the input modules, most of the time, it makes bespoke hangs.
Here is the traceboack:
```
#0  0x00007ffff74312a2 in raise () from /lib64/libc.so.6
#1  0x00007ffff741a8a4 in abort () from /lib64/libc.so.6
#2  0x00005555557aabc8 in std::__replacement_assert (__file=<optimized out>, __line=<optimized out>, __function=<optimized out>, __condition=<optimized out>)
    at /usr/include/c++/11/x86_64-redhat-linux/bits/c++config.h:2660
#3  0x0000555555a862df in std::vector<float*, std::allocator<float*> >::operator[] (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/11/bits/stl_vector.h:1043
#4  std::vector<float*, std::allocator<float*> >::operator[] (this=<optimized out>, this=<optimized out>, __n=0) at /usr/include/c++/11/bits/stl_vector.h:1043
#5  ModularSynth::GetOutputBuffer (channel=0, this=<optimized out>) at /usr/src/debug/BespokeSynth-1.1.0-7.fc34.x86_64/Source/ModularSynth.cpp:1800
#6  OutputChannel::Process (this=0x5555573fb8d0, time=<optimized out>) at /usr/src/debug/BespokeSynth-1.1.0-7.fc34.x86_64/Source/OutputChannel.cpp:105
#7  0x00005555558a8b3a in ModularSynth::AudioOut (this=0x55555624e4c0, output=0x7fffc1821090, bufferSize=256, nChannels=0) at /usr/include/c++/11/bits/stl_vector.h:1043
#8  0x0000555555bd8269 in juce::AudioDeviceManager::audioDeviceIOCallbackInt (numSamples=256, numOutputChannels=0, outputChannelData=0x7fffc1821090, numInputChannels=3, inputChannelData=0x7fffc1820fd0, 
    this=0x55555624e180) at /usr/src/debug/BespokeSynth-1.1.0-7.fc34.x86_64/libs/JUCE/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp:829
#9  juce::AudioDeviceManager::CallbackHandler::audioDeviceIOCallback (this=<optimized out>, ins=0x7fffc1820fd0, numIns=3, outs=0x7fffc1821090, numOuts=0, numSamples=256)
    at /usr/src/debug/BespokeSynth-1.1.0-7.fc34.x86_64/libs/JUCE/modules/juce_audio_devices/audio_io/juce_AudioDeviceManager.cpp:54
#10 0x0000555555bd6949 in juce::JackAudioIODevice::process (numSamples=256, this=0x7fffc06ef440) at /usr/src/debug/BespokeSynth-1.1.0-7.fc34.x86_64/libs/JUCE/modules/juce_core/memory/juce_HeapBlock.h:194
#11 juce::JackAudioIODevice::processCallback (nframes=256, callbackArgument=0x7fffc06ef440)
    at /usr/src/debug/BespokeSynth-1.1.0-7.fc34.x86_64/libs/JUCE/modules/juce_audio_devices/native/juce_linux_JackAudio.cpp:478
#12 0x00007ffff6c9ccb9 in Jack::JackClient::ExecuteThread() () from /lib64/libjack.so.0
#13 0x00007ffff6c9c3f8 in non-virtual thunk to Jack::JackClient::Execute() () from /lib64/libjack.so.0
#14 0x00007ffff6cba060 in Jack::JackPosixThread::ThreadHandler(void*) () from /lib64/libjack.so.0
#15 0x00007ffff794a299 in start_thread () from /lib64/libpthread.so.0
#16 0x00007ffff74f4353 in clone () from /lib64/libc.so.6
```

**Comment by ycollet** [comment]
Thanks a lot for the merge !
