### ISSUE TITLE
Crash on loading project

### ISSUE THREAD

**Issue by Telikan** [BespokeSynth/BespokeSynth#786]
## Describe the bug

Hi there, I created a template project which is mapped to my Akai MIDIMIX, but Bespoke crashes when trying to open. I've tried resanning VSTs and also disabling them as I have a reverb and delay send, but this didn't work. If anyone can help that would be  much appreciated!

Attached is the most recent crash report, please let me know if you need anything further.

## Build info

bespoke 1.1.0 (Nov 16 2021 11:51:26) - Mac OSX 11.6 - main bd41884b

## Steps To Reproduce

- Open bespoke
- Select 'Load'
- Open MIDIMIX project
- bespoke crashes

## Expected vs. actual behavior

[crash_2022-03-17_10-16.txt](https://github.com/BespokeSynth/BespokeSynth/files/8283801/crash_2022-03-17_10-16.txt)

**Comment by KottV** [comment]
Hi,
Crashing template will be useful to provide.

**Comment by Telikan** [comment]
Hi, sorry for not attaching in the above. Please see attached

Midimix Template 01.bsk.zip](https://github.com/BespokeSynth/BespokeSynth/files/8284440/Midimix.Template.01.bsk.zip)

**Comment by KottV** [comment]
Thanks, I'll run in debug build to see what is here.

**Comment by Telikan** [comment]
Thank you!

**Comment by KottV** [comment]
Looks it doesn't like some character in the savestate

```
_pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff76691e3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff7619306 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7602813 in __GI_abort () at abort.c:79
#4  0x00007ffff760272b in __assert_fail_base (fmt=<optimized out>, assertion=<optimized out>, file=<optimized out>, line=<optimized out>, function=<optimized out>) at assert.c:92
#5  0x00007ffff76118f6 in __GI___assert_fail (assertion=0x1244988 "separatorChar == GetModuleSeparator()[j]", file=0x1244788 "/home/kv/src/audio/BespokeSynth/Source/ModuleContainer.cpp", line=650, function=0x12448b0 "void ModuleContainer::LoadState(FileStreamIn&)") at assert.c:101
#6  0x00000000008fba5c in ModuleContainer::LoadState (this=0x1abf328, in=...) at /home/kv/src/audio/BespokeSynth/Source/ModuleContainer.cpp:650
#7  0x000000000066e06c in ModularSynth::LoadState (this=0x1abea50, file=...) at /home/kv/src/audio/BespokeSynth/Source/ModularSynth.cpp:2591
#8  0x000000000066d862 in ModularSynth::LoadStatePopupImp (this=0x1abea50) at /home/kv/src/audio/BespokeSynth/Source/ModularSynth.cpp:2526
#9  0x0000000000660153 in ModularSynth::Poll (this=0x1abea50) at /home/kv/src/audio/BespokeSynth/Source/ModularSynth.cpp:383
#10 0x0000000000624838 in MainContentComponent::timerCallback (this=0x1abe550) at /home/kv/src/audio/BespokeSynth/Source/MainComponent.cpp:125
#11 0x0000000000ca3141 in juce::Timer::TimerThread::callTimers (this=0x1ab9c70) at /usr/lib64/juce/include/JUCE-6.1.6/modules/juce_events/timers/juce_Timer.cpp:115
#12 0x0000000000ca3335 in juce::Timer::TimerThread::CallTimersMessage::messageCallback (this=0x7ffff0000c10) at /usr/lib64/juce/include/JUCE-6.1.6/modules/juce_events/timers/juce_Timer.cpp:181
#13 0x0000000000ca4d5e in juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}::operator()(int) const (__closure=0x1a95a48, fd=4) at /usr/lib64/juce/include/JUCE-6.1.6/modules/juce_events/native/juce_linux_Messaging.cpp:42
#14 0x0000000000cb4a18 in std::__invoke_impl<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>(std::__invoke_other, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int&&) (__f=...) at /usr/include/c++/11/bits/invoke.h:61
#15 0x0000000000cb1fb1 in std::__invoke_r<void, juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int>(juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}&, int&&) (__fn=...) at /usr/include/c++/11/bits/invoke.h:111
#16 0x0000000000cad898 in std::_Function_handler<void (int), juce::InternalMessageQueue::InternalMessageQueue()::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) (__functor=..., __args#0=@0x7fffffffd634: 4) at /usr/include/c++/11/bits/std_function.h:290
#17 0x0000000000ca9fe4 in std::function<void (int)>::operator()(int) const (this=0x1a95a48, __args#0=4) at /usr/include/c++/11/bits/std_function.h:590
#18 0x0000000000ca58d5 in juce::InternalRunLoop::dispatchPendingEvents (this=0x1a959c0) at /usr/lib64/juce/include/JUCE-6.1.6/modules/juce_events/native/juce_linux_Messaging.cpp:185
#19 0x0000000000ca06ba in juce::dispatchNextMessageOnSystemQueue (returnIfNoPendingMessages=false) at /usr/lib64/juce/include/JUCE-6.1.6/modules/juce_events/native/juce_linux_Messaging.cpp:299
#20 0x0000000000c9b037 in juce::MessageManager::runDispatchLoop (this=0x1a95950) at /usr/lib64/juce/include/JUCE-6.1.6/modules/juce_events/messages/juce_MessageManager.cpp:107
#21 0x0000000000c9a64d in juce::JUCEApplicationBase::main () at /usr/lib64/juce/include/JUCE-6.1.6/modules/juce_events/messages/juce_ApplicationBase.cpp:262
#22 0x0000000000c9a558 in juce::JUCEApplicationBase::main (argc=1, argv=0x7fffffffd8e8) at /usr/lib64/juce/include/JUCE-6.1.6/modules/juce_events/messages/juce_ApplicationBase.cpp:240
#23 0x000000000061cebe in main (argc=1, argv=0x7fffffffd8e8) at /home/kv/src/audio/BespokeSynth/Source/Main.cpp:133
```

@Telikan, what if you try to recreate this preset, is that issue still?

**Comment by Telikan** [comment]
Hi, thank you - I've re created the project not renaming any modules etc and it's all working! Thanks for your help!
